# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-15 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='htmlfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileobject', models.FileField(null=True, upload_to='templates/temp_files')),
                ('filename', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
