# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-15 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotmap', '0003_auto_20180615_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='htmlfile',
        ),
    ]
