# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import plotmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('plotmap', '0004_delete_htmlfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='fileobject',
            field=models.FileField(null=True, upload_to=plotmap.models.get_file_path),
        ),
    ]
